name: Deploy to Tencent COS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install coscmd
        run: pip install coscmd

      - name: config coscmd
        run: |
          coscmd config -a ${{ secrets.COS_SECRET_ID }} -s ${{ secrets.COS_SECRET_KEY }} -b woainanjing-1352026585 -r ap-shanghai

      - name: upload static files (ignore git folders)
        run: coscmd upload -rs ./ / --ignore ".git/*,.github/*"

      - name: clean cloud files not exist locally (-f skip confirm)
        run: echo "y" | coscmd delete -r / --config-dir ~/.coscmd
